# Generated inputs stay in the dedicated build-test folder; no models needed.
file(MAKE_DIRECTORY "${TEST_DIR}")
function(check_manifest name contents expected)
    set(path "${TEST_DIR}/${name}.toml")
    file(WRITE "${path}" "${contents}")
    execute_process(COMMAND "${OCR_EXECUTABLE}" --validate-manifest "${path}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(expected STREQUAL "valid")
        if(NOT result EQUAL 0 OR NOT output MATCHES "Valid labels")
            message(FATAL_ERROR "${name}: ${result} ${output} ${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "${name}: wrong rejection: ${result} ${output} ${error}")
    endif()
endfunction()
set(header "schema_version = 1\n[[samples]]\nid = 'one'\nimage = 'not-required.png'\nwidth = 100\nheight = 50\n")
check_manifest(valid "${header}regions = [{text='canon',box=[0,0,30,20]}]" valid)
check_manifest(negative "${header}regions = []" valid)
check_manifest(unicode "${header}regions = [{text='Türkçe',box=[0,0,30,20]}]" "lowercase")
check_manifest(empty_text "${header}regions = [{text='',box=[0,0,30,20]}]" "manifest string")
check_manifest(outside "${header}regions = [{text='a',box=[95,0,30,20]}]" "exceeds image")
check_manifest(missing_regions "${header}" "regions array")
check_manifest(non_numeric "${header}regions = [{text='a',box=['x',0,30,20]}]" "numeric")
check_manifest(zero_box "${header}regions = [{text='a',box=[0,0,0,20]}]" "Invalid evaluation box")
check_manifest(duplicate "${header}regions = []\n[[samples]]\nid='one'\n" "Duplicate sample id")
check_manifest(empty "schema_version = 1\nsamples = []\n" "1..1000")
