# Optional dependencies never affect the dependency-free core build.
include(FetchContent)
FetchContent_Declare(search_json URL https://codeload.github.com/nlohmann/json/tar.gz/9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03 URL_HASH SHA256=0dbc5e40a01ff142e7e68c03e85247a4dcede2f592d12d3677dee3664d17975a DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(search_http URL https://codeload.github.com/yhirose/cpp-httplib/tar.gz/a7bc00e3307fecdb4d67545e93be7b88cfb1e186 URL_HASH SHA256=ec95cbfb4dac7cd423d1f1056028341f836fa866b0d5a3d171635e74f13efd7a DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(search_sha URL https://codeload.github.com/okdshin/PicoSHA2/tar.gz/161cb3fc4170fa7a3eca9e582cebd27cc4d1fe29 URL_HASH SHA256=6cf473a00c98298d3ddee0aed853e3c799791f49dbc01c996ea46cb248e85802 DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
set(HTTPLIB_USE_OPENSSL_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_ZLIB_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_BROTLI_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(search_json search_http search_sha)
find_package(ICU REQUIRED COMPONENTS uc i18n)
set(ONNXRUNTIME_ROOT "" CACHE PATH "Extracted ONNX Runtime C/C++ CPU distribution")
find_path(ORT_INCLUDE onnxruntime_cxx_api.h PATHS "${ONNXRUNTIME_ROOT}/include" REQUIRED NO_DEFAULT_PATH)
find_library(ORT_LIBRARY NAMES onnxruntime PATHS "${ONNXRUNTIME_ROOT}/lib" REQUIRED NO_DEFAULT_PATH)
add_library(aegis_ort SHARED IMPORTED)
if(WIN32)
    set_target_properties(aegis_ort PROPERTIES IMPORTED_IMPLIB "${ORT_LIBRARY}" IMPORTED_LOCATION "${ONNXRUNTIME_ROOT}/lib/onnxruntime.dll")
else()
    set_target_properties(aegis_ort PROPERTIES IMPORTED_LOCATION "${ORT_LIBRARY}")
endif()
set_target_properties(aegis_ort PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${ORT_INCLUDE}")
add_library(aegisvision_search src/clip.cpp src/clip_tokenizer.cpp src/qdrant.cpp src/search_benchmark.cpp src/indexing.cpp)
target_include_directories(aegisvision_search PRIVATE "${search_sha_SOURCE_DIR}")
target_link_libraries(aegisvision_search PUBLIC aegisvision_opencv nlohmann_json::nlohmann_json PRIVATE aegis_ort ICU::uc ICU::i18n httplib::httplib)
add_executable(aegisvision_search_cli apps/search.cpp)
target_link_libraries(aegisvision_search_cli PRIVATE aegisvision_search aegisvision_configuration)
function(aegis_search_runtime target)
    aegisvision_runtime(${target})
    if(WIN32)
        # FindICU provides import libraries, not DLL locations.
        file(GLOB _icu_dlls "${ICU_ROOT}/bin64/icu*.dll")
        if(NOT _icu_dlls)
            message(FATAL_ERROR "Set ICU_ROOT to the ICU Windows distribution (with bin64)")
        endif()
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different ${_icu_dlls} $<TARGET_FILE_DIR:${target}> COMMAND_EXPAND_LISTS)
    endif()
endfunction()
aegis_search_runtime(aegisvision_search_cli)
find_package(Threads REQUIRED)
enable_language(C)
FetchContent_Declare(job_sqlite URL https://sqlite.org/2026/sqlite-amalgamation-3530400.zip URL_HASH SHA3_256=628a44cfe82c66aed1ccbbe85a562d2e33ebe64b3288981ed76285612227934e DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(job_sqlite)
add_library(aegis_job_sqlite STATIC "${job_sqlite_SOURCE_DIR}/sqlite3.c")
target_include_directories(aegis_job_sqlite SYSTEM PUBLIC "${job_sqlite_SOURCE_DIR}")
target_compile_definitions(aegis_job_sqlite PRIVATE SQLITE_THREADSAFE=1 SQLITE_OMIT_LOAD_EXTENSION=1)
target_link_libraries(aegis_job_sqlite PRIVATE Threads::Threads ${CMAKE_DL_LIBS})
add_library(aegisvision_service src/jobs.cpp src/job_store.cpp src/service.cpp src/live_session.cpp)
target_link_libraries(aegisvision_service PUBLIC aegisvision_search httplib::httplib Threads::Threads PRIVATE aegis_job_sqlite)
add_executable(aegisvision_server apps/server.cpp)
target_link_libraries(aegisvision_server PRIVATE aegisvision_service aegisvision_configuration)
aegis_search_runtime(aegisvision_server)
if(WIN32 AND _opencv_ffmpeg)
    add_custom_command(TARGET aegisvision_search_cli POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${_opencv_ffmpeg}
            $<TARGET_FILE_DIR:aegisvision_search_cli> COMMAND_EXPAND_LISTS)
    add_custom_command(TARGET aegisvision_server POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${_opencv_ffmpeg}
            $<TARGET_FILE_DIR:aegisvision_server> COMMAND_EXPAND_LISTS)
endif()
if(AEGISVISION_BUILD_TESTS)
    add_executable(aegisvision_job_persistence_tests tests/test_job_persistence.cpp)
    target_link_libraries(aegisvision_job_persistence_tests PRIVATE aegisvision_service)
    aegis_search_runtime(aegisvision_job_persistence_tests)
    add_test(NAME aegisvision_job_persistence COMMAND aegisvision_job_persistence_tests)
    add_test(NAME aegisvision_job_crash COMMAND aegisvision_job_persistence_tests --crash "${CMAKE_CURRENT_BINARY_DIR}/job-crash-fixture.sqlite")
    add_test(NAME aegisvision_job_recover COMMAND aegisvision_job_persistence_tests --recover "${CMAKE_CURRENT_BINARY_DIR}/job-crash-fixture.sqlite")
    set_tests_properties(aegisvision_job_crash PROPERTIES FIXTURES_SETUP job_crash TIMEOUT 20)
    set_tests_properties(aegisvision_job_recover PROPERTIES FIXTURES_REQUIRED job_crash TIMEOUT 20)
    add_executable(aegisvision_service_tests tests/test_service.cpp)
    target_link_libraries(aegisvision_service_tests PRIVATE aegisvision_service)
    aegis_search_runtime(aegisvision_service_tests)
    add_test(NAME aegisvision_service COMMAND aegisvision_service_tests)
    add_executable(aegisvision_live_service_tests tests/test_live_service.cpp)
    target_link_libraries(aegisvision_live_service_tests PRIVATE aegisvision_service)
    aegis_search_runtime(aegisvision_live_service_tests)
    add_test(NAME aegisvision_live_service COMMAND aegisvision_live_service_tests)
    set_tests_properties(aegisvision_live_service PROPERTIES TIMEOUT 30)
    add_test(NAME aegisvision_server_help COMMAND aegisvision_server --help)
    add_executable(aegisvision_indexing_tests tests/test_indexing.cpp)
    target_link_libraries(aegisvision_indexing_tests PRIVATE aegisvision_search)
    aegis_search_runtime(aegisvision_indexing_tests)
    add_test(NAME aegisvision_indexing COMMAND aegisvision_indexing_tests)
    add_executable(aegisvision_search_tests tests/test_search.cpp)
    target_link_libraries(aegisvision_search_tests PRIVATE aegisvision_search httplib::httplib)
    aegis_search_runtime(aegisvision_search_tests)
    add_test(NAME aegisvision_search_unit COMMAND aegisvision_search_tests)
    add_test(NAME aegisvision_search_help COMMAND aegisvision_search_cli --help)
    set(AEGISVISION_CLIP_BUNDLE "" CACHE PATH "Optional exported CLIP bundle for reference tests")
    if(AEGISVISION_CLIP_BUNDLE)
        add_test(NAME aegisvision_clip_reference COMMAND aegisvision_search_tests "${AEGISVISION_CLIP_BUNDLE}")
    endif()
endif()
