# Optional dependencies never affect the dependency-free core build.
include(FetchContent)
FetchContent_Declare(search_json URL https://codeload.github.com/nlohmann/json/tar.gz/9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03 URL_HASH SHA256=0dbc5e40a01ff142e7e68c03e85247a4dcede2f592d12d3677dee3664d17975a DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(search_http URL https://codeload.github.com/yhirose/cpp-httplib/tar.gz/a7bc00e3307fecdb4d67545e93be7b88cfb1e186 URL_HASH SHA256=ec95cbfb4dac7cd423d1f1056028341f836fa866b0d5a3d171635e74f13efd7a DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(search_sha URL https://codeload.github.com/okdshin/PicoSHA2/tar.gz/161cb3fc4170fa7a3eca9e582cebd27cc4d1fe29 URL_HASH SHA256=6cf473a00c98298d3ddee0aed853e3c799791f49dbc01c996ea46cb248e85802 DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
set(HTTPLIB_USE_OPENSSL_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_ZLIB_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_BROTLI_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(search_json search_http search_sha)
find_package(ICU REQUIRED COMPONENTS uc i18n)
set(ONNXRUNTIME_ROOT "" CACHE PATH "Extracted ONNX Runtime C/C++ CPU distribution")
find_path(ORT_INCLUDE onnxruntime_cxx_api.h PATHS "${ONNXRUNTIME_ROOT}/include" REQUIRED NO_DEFAULT_PATH)
find_library(ORT_LIBRARY NAMES onnxruntime PATHS "${ONNXRUNTIME_ROOT}/lib" REQUIRED NO_DEFAULT_PATH)
add_library(aegis_ort SHARED IMPORTED)
if(WIN32)
    set_target_properties(aegis_ort PROPERTIES IMPORTED_IMPLIB "${ORT_LIBRARY}" IMPORTED_LOCATION "${ONNXRUNTIME_ROOT}/lib/onnxruntime.dll")
else()
    set_target_properties(aegis_ort PROPERTIES IMPORTED_LOCATION "${ORT_LIBRARY}")
endif()
set_target_properties(aegis_ort PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${ORT_INCLUDE}")
add_library(aegisvision_search src/clip.cpp src/clip_tokenizer.cpp src/qdrant.cpp)
target_include_directories(aegisvision_search PRIVATE "${search_sha_SOURCE_DIR}")
target_link_libraries(aegisvision_search PUBLIC aegisvision_opencv nlohmann_json::nlohmann_json PRIVATE aegis_ort ICU::uc ICU::i18n httplib::httplib)
add_executable(aegisvision_search_cli apps/search.cpp)
target_link_libraries(aegisvision_search_cli PRIVATE aegisvision_search aegisvision_configuration)
function(aegis_search_runtime target)
    aegisvision_runtime(${target})
    if(WIN32)
        # FindICU provides import libraries, not DLL locations.
        file(GLOB _icu_dlls "${ICU_ROOT}/bin64/icu*.dll")
        if(NOT _icu_dlls)
            message(FATAL_ERROR "Set ICU_ROOT to the ICU Windows distribution (with bin64)")
        endif()
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different ${_icu_dlls} $<TARGET_FILE_DIR:${target}> COMMAND_EXPAND_LISTS)
    endif()
endfunction()
aegis_search_runtime(aegisvision_search_cli)
if(AEGISVISION_BUILD_TESTS)
    add_executable(aegisvision_search_tests tests/test_search.cpp)
    target_link_libraries(aegisvision_search_tests PRIVATE aegisvision_search httplib::httplib)
    aegis_search_runtime(aegisvision_search_tests)
    add_test(NAME aegisvision_search_unit COMMAND aegisvision_search_tests)
    add_test(NAME aegisvision_search_help COMMAND aegisvision_search_cli --help)
    set(AEGISVISION_CLIP_BUNDLE "" CACHE PATH "Optional exported CLIP bundle for reference tests")
    if(AEGISVISION_CLIP_BUNDLE)
        add_test(NAME aegisvision_clip_reference COMMAND aegisvision_search_tests "${AEGISVISION_CLIP_BUNDLE}")
    endif()
endif()
